const GET_INIT_CARDLINES = 'GET_INIT_CARDLINES';
const UPDATE_MISSION_TIME = 'UPDATE_MISSION_TIME';
const UPDATE_CURRENT_MISSION = 'UPDATE_CURRENT_MISSION'
const UPDATE_BREAK_STATUS = 'UPDATE_BREAK_STATUS';
const UPDATE_RINGTONES = 'UPDATE_RINGTONES';

module.exports = {
	GET_INIT_CARDLINES, UPDATE_MISSION_TIME, UPDATE_CURRENT_MISSION, UPDATE_BREAK_STATUS, UPDATE_RINGTONES
};