const UPDATE_SELECTED_ITEM = 'UPDATE_SELECTED_ITEM';
const UPDATE_BOOKMARK = 'UPDATE_BOOKMARK';
const UPDATE_VIEW_TYPE = 'UPDATE_VIEW_TYPE';
const DELETE_ITEM = 'DELETE_ITEM';
const ADD_NOTE = 'ADD_NOTE';
const UPDATE_NOTE = 'UPDATE_NOTE';
const ADD_CATEGORY = 'ADD_CATEGORY';
const UPDATE_SELECTED_CATEGORY = 'UPDATE_SELECTED_CATEGORY';
const UPDATE_SELECTED_NOTE = 'UPDATE_SELECTED_NOTE';

module.exports = {
	UPDATE_SELECTED_ITEM,UPDATE_BOOKMARK,UPDATE_VIEW_TYPE,
	DELETE_ITEM,ADD_NOTE,UPDATE_NOTE,ADD_CATEGORY,UPDATE_SELECTED_CATEGORY,UPDATE_SELECTED_NOTE
};