const UPDATE_SEARCH = 'UPDATE_SEARCH';
const UPDATE_SELECTED_DRIVE = 'UPDATE_SELECTED_DRIVE';
const UPDATE_SELECTED_ITEM = 'UPDATE_SELECTED_ITEM';
const UPDATE_BOOKMARK = 'UPDATE_BOOKMARK';
const ADD_NEW_ITEM = 'ADD_NEW_ITEM';
const UPDATE_VIEW_TYPE = 'UPDATE_VIEW_TYPE';
const DELETE_ITEM = 'DELETE_ITEM';
const ADD_NOTE = 'ADD_NOTE';
const ADD_CATEGORY = 'ADD_CATEGORY';
const UPDATE_SELECTED_CATEGORY = 'UPDATE_SELECTED_CATEGORY';
const UPDATE_SELECTED_NOTE = 'UPDATE_SELECTED_NOTE';

module.exports = {
	UPDATE_SEARCH,UPDATE_SELECTED_DRIVE,UPDATE_SELECTED_ITEM,UPDATE_BOOKMARK,ADD_NEW_ITEM,UPDATE_VIEW_TYPE,
	DELETE_ITEM,ADD_NOTE,ADD_CATEGORY,UPDATE_SELECTED_CATEGORY,UPDATE_SELECTED_NOTE
};