const REQUEST_ROOMS = 'REQUEST_ROOMS';
const RECEIVE_ROOMS = 'RECEIVE_ROOMS';
const REQUEST_ROOM_DETAIL = 'REQUEST_ROOM_DETAIL';
const RECEIVE_ROOM_DETAIL = 'RECEIVE_ROOM_DETAIL';
const BOOK_ROOM_RESULT = 'BOOK_ROOM_RESULT';
const REQUEST_BOOK_ROOM = 'REQUEST_BOOK_ROOM';
const RESET_BOOK_RESULT = 'RESET_BOOK_RESULT';

module.exports = {
	REQUEST_ROOMS, RECEIVE_ROOMS, REQUEST_ROOM_DETAIL, RECEIVE_ROOM_DETAIL, 
	BOOK_ROOM_RESULT, REQUEST_BOOK_ROOM, RESET_BOOK_RESULT
};