const UPDATE_FAVORITE = 'UPDATE_FAVORITE';
const UPDATE_CURRENT_PLAY = 'UPDATE_CURRENT_PLAY';
const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE';
const UPDATE_CURRENT_ALBUM = 'UPDATE_CURRENT_ALBUM';

module.exports = {
	UPDATE_FAVORITE, UPDATE_CURRENT_PLAY, UPDATE_CURRENT_PAGE, UPDATE_CURRENT_ALBUM
};