const UPDATE_FAVORITE = 'UPDATE_FAVORITE';
const UPDATE_CURRENT_PLAY = 'UPDATE_CURRENT_PLAY';
const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE';
const UPDATE_CURRENT_ALBUM = 'UPDATE_CURRENT_ALBUM';
const UPDATE_PLAY_TIME = 'UPDATE_PLAY_TIME';
const UPDATE_PLAY_LOOP = 'UPDATE_PLAY_LOOP';
const UPDATE_PLAY_RANDOM = 'UPDATE_PLAY_RANDOM';
const UPDATE_PLAY_VOLUME = 'UPDATE_PLAY_VOLUME';
const UPDATE_PLAY_STATUS = 'UPDATE_PLAY_STATUS';

module.exports = {
	UPDATE_FAVORITE, UPDATE_CURRENT_PLAY, UPDATE_CURRENT_PAGE, UPDATE_CURRENT_ALBUM,
	UPDATE_PLAY_TIME, UPDATE_PLAY_LOOP, UPDATE_PLAY_RANDOM, UPDATE_PLAY_VOLUME, UPDATE_PLAY_STATUS
};