const ADD_MISSION = 'ADD_MISSION';
const UPDATE_MISSION_STATUS = 'UPDATE_MISSION_STATUS';
const UPDATE_BREAK_STATUS = 'UPDATE_BREAK_STATUS';
const UPDATE_RINGTONES = 'UPDATE_RINGTONES';

module.exports = {
	ADD_MISSION, UPDATE_MISSION_STATUS, UPDATE_BREAK_STATUS, UPDATE_RINGTONES
};