import tr_1 from '../svg/Cards/tr_1.svg'
import tr_2 from '../svg/Cards/tr_2.svg'
import tr_3 from '../svg/Cards/tr_3.svg'
import tr_4 from '../svg/Cards/tr_4.svg'
import tr_5 from '../svg/Cards/tr_5.svg'
import tr_6 from '../svg/Cards/tr_6.svg'
import tr_7 from '../svg/Cards/tr_7.svg'
import tr_8 from '../svg/Cards/tr_8.svg'
import tr_9 from '../svg/Cards/tr_9.svg'
import tr_10 from '../svg/Cards/tr_10.svg'
import tr_11 from '../svg/Cards/tr_11.svg'
import tr_12 from '../svg/Cards/tr_12.svg'
import tr_13 from '../svg/Cards/tr_13.svg'

import pi_1 from '../svg/Cards/pi_1.svg'
import pi_2 from '../svg/Cards/pi_2.svg'
import pi_3 from '../svg/Cards/pi_3.svg'
import pi_4 from '../svg/Cards/pi_4.svg'
import pi_5 from '../svg/Cards/pi_5.svg'
import pi_6 from '../svg/Cards/pi_6.svg'
import pi_7 from '../svg/Cards/pi_7.svg'
import pi_8 from '../svg/Cards/pi_8.svg'
import pi_9 from '../svg/Cards/pi_9.svg'
import pi_10 from '../svg/Cards/pi_10.svg'
import pi_11 from '../svg/Cards/pi_11.svg'
import pi_12 from '../svg/Cards/pi_12.svg'
import pi_13 from '../svg/Cards/pi_13.svg'

import cc_1 from '../svg/Cards/cc_1.svg'
import cc_2 from '../svg/Cards/cc_2.svg'
import cc_3 from '../svg/Cards/cc_3.svg'
import cc_4 from '../svg/Cards/cc_4.svg'
import cc_5 from '../svg/Cards/cc_5.svg'
import cc_6 from '../svg/Cards/cc_6.svg'
import cc_7 from '../svg/Cards/cc_7.svg'
import cc_8 from '../svg/Cards/cc_8.svg'
import cc_9 from '../svg/Cards/cc_9.svg'
import cc_10 from '../svg/Cards/cc_10.svg'
import cc_11 from '../svg/Cards/cc_11.svg'
import cc_12 from '../svg/Cards/cc_12.svg'
import cc_13 from '../svg/Cards/cc_13.svg'

import ca_1 from '../svg/Cards/ca_1.svg'
import ca_2 from '../svg/Cards/ca_2.svg'
import ca_3 from '../svg/Cards/ca_3.svg'
import ca_4 from '../svg/Cards/ca_4.svg'
import ca_5 from '../svg/Cards/ca_5.svg'
import ca_6 from '../svg/Cards/ca_6.svg'
import ca_7 from '../svg/Cards/ca_7.svg'
import ca_8 from '../svg/Cards/ca_8.svg'
import ca_9 from '../svg/Cards/ca_9.svg'
import ca_10 from '../svg/Cards/ca_10.svg'
import ca_11 from '../svg/Cards/ca_11.svg'
import ca_12 from '../svg/Cards/ca_12.svg'
import ca_13 from '../svg/Cards/ca_13.svg'


